version: 1.0.5
enable: true
peaceful:
  CheckDelay: 86400
  StartDelay: 1
easy:
  CheckDelay: 10
  StartDelay: 20
medium:
  CheckDelay: 7
  StartDelay: 14
hard:
  CheckDelay: 4
  StartDelay: 8
CheckRadius: 2
HouseRecognizer: cross
debug-mode: false