version: 1.0.7

#Winter biomes options
winter:
  enable: true
  HouseRecognizer: cross
  CheckRadius: 2
  PlayerDamage:
    FullArmor: 0
    ThreePieces: 1
    TwoPieces: 2
    OnePiece: 2
    NoArmor: 3
    
#Desert biome options
desert:
  enable: false
  HouseRecognizer: simple
  NumberOfCheckPerFoodLost: 5
  StaminaLost:
    WithHelmet: [0.1F]
    WithoutHelmet: [0.3F]
  StaminaReplenishWaterBottle: [1.0F]
    
#Settings related to difficulty in your main world.
peaceful:
  CheckDelay: 86400
  StartDelay: 1
easy:
  CheckDelay: 10
  StartDelay: 20
medium:
  CheckDelay: 7
  StartDelay: 14
hard:
  CheckDelay: 4
  StartDelay: 8
  
#Write down here IDs of items which can proteck you. You can add here your IDs of items from mods.
Armor:
  Boots: [301, 305, 309, 313, 317]
  Chestplate: [299, 303, 307, 311, 315]
  Helmet: [298, 302, 306, 310, 314]
  Leggings: [300, 304, 308, 312, 316]

#Chat related functions
NumberOfChecksPerWarningMessage: 5
debug-mode: true